# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:


- task: Maven@3
  inputs:
    mavenPomFile: 'react-and-spring-data-rest/pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false


- task: Maven@3
  displayName: Build Docker image
  inputs:
    mavenPomFile: 'react-and-spring-data-rest/pom.xml'
    goals: 'spring-boot:build-image'
    publishJUnitResults: false
    jdkVersionOption: '1.11'


- task: Docker@2
  inputs:
    containerRegistry: 'ACRConnection'
    repository: 'react-and-spring-data-rest'
    command: 'push'
    tags: 'latest'